--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TobyDev265/LuckyPlayer
build-by-default: true
branches:
- main
projects:
  LuckyPlayer:
    path: ""
    icon: icon.png
    libs:
    - src: JackMD\UpdateNotifier\UpdateNotifier
      version: ^2.1.0
...
